"""empty message

Revision ID: d7e5c9c5b8fd
Revises: b9cd33a040f5
Create Date: 2020-10-05 14:43:01.110927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e5c9c5b8fd'
down_revision = 'b9cd33a040f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars_company', sa.Column('car_id', sa.Integer(), nullable=True))
    op.drop_constraint('cars_company_request_id_fkey', 'cars_company', type_='foreignkey')
    op.create_foreign_key(None, 'cars_company', 'cars', ['car_id'], ['id'])
    op.drop_column('cars_company', 'request_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars_company', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cars_company', type_='foreignkey')
    op.create_foreign_key('cars_company_request_id_fkey', 'cars_company', 'cars', ['request_id'], ['id'])
    op.drop_column('cars_company', 'car_id')
    # ### end Alembic commands ###
